name: Deploy NestJS User Service App

on:
  push:
    branch: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: create .env.dev
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: '3306'
          DB_USER: 'root'
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: 'moonshot'
        run: |
          echo -e "DB_HOST=$DB_HOST\nDB_PORT=$DB_PORT\nDB_USER=$DB_USER\nDB_PASSWORD=$DB_PASSWORD\nDB_DATABASE=$DB_DATABASE" > .env.test

      - name: Set up Docker Build
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/moonshot-user-service:latest
            ${{ secrets.DOCKER_USERNAME }}/moonshot-user-service:${{ github.sha }}