name: Fly Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: create .env.dev
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_PORT: '3306'
          DB_USER: 'root'
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_DATABASE: 'moonshot'
        run: |
          echo -e "DB_HOST=$DB_HOST\nDB_PORT=$DB_PORT\nDB_USER=$DB_USER\nDB_PASSWORD=$DB_PASSWORD\nDB_DATABASE=$DB_DATABASE" > .env.dev

      - uses: actions/checkout@v3
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}